Handle method adding (broken) and lazy interface enumeration
TODO - this doesn't work for a couple of reasons
 - The proxy class is never added to the class loader
 - Transforming classes on loaders above us causes `NoClassDefFoundError`s because they try and load mixin classes (e.g. `CallbackInfo`)